FROM python:3.10-slim-bullseye

# Set separate working directory for easier debugging.
WORKDIR /app

RUN pip install --no-cache-dir 'poetry==1.2.1'
COPY pyproject.toml poetry.lock ./
# Install the dependencies first, so that we can cache them.
RUN poetry install --with test --extras postgres

# Copy everything. (Note: If needed, we can use .dockerignore to limit what's copied.)
COPY . .

# Install again, now that we've copied the dbt-osmosis package files. Otherwise,
# dbt-osmosis itself won't be installed.
RUN poetry install --with test --extras postgres
