#!/usr/bin/env bash
my_path="$( cd "$(dirname "$0")"; pwd -P)"
#docker-compose -f ${my_path}/docker-compose.yml exec app bash
docker compose -f docker/docker-compose.yml exec app bash -c "SHELL=bash poetry shell"
