name: "jaffle_shop_duckdb"

config-version: 2
version: "0.1"

profile: "jaffle_shop"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"
  - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop_duckdb:
    +dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"
    materialized: table
    staging:
      materialized: view

seeds:
  jaffle_shop_duckdb:
    +dbt-osmosis: "{node.database}/{node.schema}/{node.name}.yml"

flags: {}

vars:
  dbt-osmosis:
    yaml_settings:
      map_indent: 2
      sequence_indent: 4
      brace_single_entry_mapping_in_flow_sequence: true
      explicit_start: true
