jaffle_shop:
  target: dev
  outputs:
    dev:
      type: sqlite
      threads: 1
      database: "main"
      schema: "main"
      schemas_and_paths:
        main: "demo_sqlite/jaffle_shop.db"
      schema_directory: "demo_sqlite/"
