name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: |
          pip install --constraint=.github/workflows/constraints.txt pip
          pip --version

      - name: Install uv
        run: |
          pip install --constraint=.github/workflows/constraints.txt uv
          uv --version

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          sha="$(git rev-parse --verify --quiet HEAD^)"
          echo "sha=${sha:?}" >> "$GITHUB_OUTPUT"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |
            sed -nE 's/^version = "([^"]+)"/\1/p' pyproject.toml

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          sed -i -E "s/^version\s*=\s*\"[^\"]+\"/version = \"1.0.0.dev.$(date +%Y%m%d)\"/" pyproject.toml

      - name: Build package
        run: |
          uvx --from=hatchling==1.26.3 hatchling build

      - name: Publish package on PyPI
        if: steps.check-version.outputs.tag
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}

      # - name: Publish package on TestPyPI
      #   if: "! steps.check-version.outputs.tag"
      #   uses: pypa/gh-action-pypi-publish@v1.13.0
      #   with:
      #     user: __token__
      #     password: ${{ secrets.TEST_PYPI_TOKEN }}
      #     repository_url: https://test.pypi.org/legacy/

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v5.23.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
